### PR TITLE
save sync button exposed in action bar for mobile and inside TVHomeFragment for TV

### LINKED ISSUE #325: Expose save sync button inside
Lemuroid has Google Drive save sync triggered automatically when the application starts and ~15 minutes after a gaming session is completed.

This works well in most cases, but there might be a need to trigger a manual scan every now and then. This is already possible by going into the cloud settings menu, but it requires 3 taps.

A better approach might be exposing inside the ActionBar a "Save Sync" button, only when cloud saves are activated.

The triggered work in this case is **SaveSyncWork.kt**, and the action should be exposed inside **menu_mobile_settings.xml**. For the Android TV counterpart the button should probably be in **SETTINGS_ADAPTER** inside **TVHomeFragment.kt**.

### PR DESCRIPTION
**Pull request by Devendra34**
Fixes #325
Thanks for detailed info about what exactly needs to be done inside the code. It helped a lot and saved my time for searching inside the project.

### CODE REVIEW

**Comment by Devendra34** [comment]
Hi @Swordfish90, please help me to understand. Do I require "builded-core"  module for the scope of this issue?
I don't have it currently

**Comment by Swordfish90** [comment]
Hi @Devendra34 . Lemuroid has two possible flavour dimensions:

1) **free** or **play**. When free no Google dependencies will be included, so the users will not be able to sync saves.

2) **bundled** or **dynamic**. When using bundled, cores are included in the APK you're building, when dynamic, they are downloaded from GitHub or Google Play if free or play.

In this case I suggest you to test the freeDynamic variant (which should not allow synching saves) and the playBundled one (which should allow it).

You can check the two implementations of  *SaveSyncManagerImpl.kt* to see how these differences are managed and do something similar.

**Comment by Devendra34** [comment]
> Hi @Devendra34 . Lemuroid has two possible flavour dimensions:
> 
> 1. **free** or **play**. When free no Google dependencies will be included, so the users will not be able to sync saves.
> 2. **bundled** or **dynamic**. When using bundled, cores are included in the APK you're building, when dynamic, they are downloaded from GitHub or Google Play if free or play.
> 
> In this case I suggest you to test the freeDynamic variant (which should not allow synching saves) and the playBundled one (which should allow it).
> 
> You can check the two implementations of _SaveSyncManagerImpl.kt_ to see how these differences are managed and do something similar.

Thanks a lot for helping me out!
I was checking the Impl of SaveSyncManager only. I have pushed the changes that fixes the above issue, of not showing the action button in "non supported" and "not configured" cases. Can you please have a look. Thanks

**Comment by Swordfish90** [comment]
Thank you very much @Devendra34 . Everything looks good now. I've also added the hacktoberfest tag in case you need it.

**Pull request merged**
